### ISSUE TITLE
Merge with master?

### ISSUE THREAD

**Issue by darksylinc** [Gundersanne/portaudio_opensles#10]
I've noticed the last commit is from 2017, and there's a few experimental changes from 2018 in the [formats branch](https://github.com/Gundersanne/portaudio_opensles/tree/formats)

If people are interested, I've [merged opensles fork with master](https://github.com/darksylinc/portaudio_opensles/tree/merge-with-master) from Feb 2021 (that's what I've been using). I can submit a PR if there's interest.

I'm still testing and so far so good.

**Comment by Gundersanne** [comment]
Ah neat! It's been a while indeed since I've worked on this.

Yea please open a PR would love to review it. I'll try to make some time to review #9 as well. And maybe finish up that formats branch sometime.

**Comment by darksylinc** [comment]
PR submitted!

>  I'm also happy to rebase it myself, it looks like a relatively painless one.

Looking at the size of the PR, it looks like perhaps a rebase may be a better approach than a merge.

**Comment by Gundersanne** [comment]
yea I'll just rebase it; and i might push it to a different branch from master right now. This was originally developed for https://github.com/exporl/apex/ and I want to give them a headsup. Which is why I also made the v1 tag.

**Comment by Gundersanne** [comment]
Included your fix in the v1 tag, I'll rebase the whole thing tomorrow, get the formats branch in depending on the work remaining and see if portaudio is interested in this fork.

**Comment by Gundersanne** [comment]
Done in the https://github.com/Gundersanne/portaudio_opensles/tree/opensles-pr-candidate branch; I need to test this some more and not entirely sure yet about all the commits in that branch, but it's rebased.
