### ISSUE TITLE
Need build tutorial for android armv7-aon windows

### ISSUE THREAD

**Issue by PlusMixDev** [Gundersanne/portaudio_opensles#8]
I'm very confuse how i can build this or crosscompile by ndk

**Comment by Gundersanne** [comment]
Please check out the readme under https://github.com/Gundersanne/portaudio_opensles/tree/opensles-pr-candidate/src/hostapi/opensles ; I added a small building section (for the https://github.com/Gundersanne/portaudio_opensles/tree/opensles-pr-candidate/src/hostapi/opensles branch only).
